name: Bug Report
description: 报告插件中的缺陷，帮助我改进。
title: '[BUG] 简短描述问题'
labels: ['bug', 'needs-triage']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查列表
      description: 请确认以下事项。
      options:
        - label: 我已搜索现有的 Issue。
          required: true
        - label: 我已尝试使用最新版本的插件。
          required: true
        - label: 我已确认这不是一个配置问题或上游服务问题。
          required: true
  
  - type: dropdown
    id: koishi_version
    attributes:
      label: Koishi 版本
      options:
        - Koishi v4.x
        - Koishi v3.x
        - 其他 (请在下方补充)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 发生问题的适配器/平台
      options:
        - onebot
        - discord
        - telegram
        - other
    validations:
      required: true
      
  - type: dropdown
    id: service_affected
    attributes:
      label: 哪个聚合服务受影响？
      description: (请选择导致问题的具体服务)
      options:
        - Saucenao
        - Ascii2d
        - Iqdb
        - Trace.moe
        - Yandex
        - Soutubot
        - Yande.re
        - Gelbooru
        - Danbooru
        - Pixiv
        - 全部/核心逻辑
      multiple: true 
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 请详细描述如何复现这个问题 (包括您使用的命令和配置)。
      placeholder: |
        1. 在平台 X 上，配置服务 Y 的 API Key。
        2. 发送命令 `sauce <图片>`。
        3. 发生错误/结果不正确。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 实际错误或 Koishi 日志
      description: 请粘贴相关的错误信息、 Koishi 控制台日志或者截图快照。
      render: markdown
    validations:
      required: false