name: Feature Request / Enhancement ✨
description: 提交一个新的功能请求或建议。
title: '[FEAT] 简短描述您想要的功能'
labels: ['feature-request']

body:
  
  - type: dropdown
    id: type
    attributes: 
      label: 功能类型
      options:
        - 新增聚合服务支持
        - 现有服务优化
        - 插件配置优化
        - 输出格式或交互改进
        - 其他
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: 功能描述
      description: 请详细描述您想要的功能。
      placeholder: 请提供详细的描述，包括功能如何工作，以及任何技术细节。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 为什么需要这个功能？(用例)
      description: 请说明添加这个功能的价值，它能解决您或用户群的什么问题？
      render: markdown
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您目前是如何解决这个需求的？或者是否有其他插件/工具可以替代？
      render: markdown
    validations:
      required: false